// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd4rpHwu4O0esMmwlkJy3CKDJoOu-n5Lc',
    appId: '1:373846261026:web:62e57eca1e9418e585f97b',
    messagingSenderId: '373846261026',
    projectId: 'fir-storage-9bb2f',
    authDomain: 'fir-storage-9bb2f.firebaseapp.com',
    storageBucket: 'fir-storage-9bb2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8Zwk-IYT63vU0CTN639p6dYfKZ8qIKU',
    appId: '1:373846261026:android:a798313c7e687a9c85f97b',
    messagingSenderId: '373846261026',
    projectId: 'fir-storage-9bb2f',
    storageBucket: 'fir-storage-9bb2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkY-4tjBPnj4kDYrjJTky1tAh0jBQxgpk',
    appId: '1:373846261026:ios:b436570b0b90c55285f97b',
    messagingSenderId: '373846261026',
    projectId: 'fir-storage-9bb2f',
    storageBucket: 'fir-storage-9bb2f.firebasestorage.app',
    iosBundleId: 'com.example.listapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkY-4tjBPnj4kDYrjJTky1tAh0jBQxgpk',
    appId: '1:373846261026:ios:b436570b0b90c55285f97b',
    messagingSenderId: '373846261026',
    projectId: 'fir-storage-9bb2f',
    storageBucket: 'fir-storage-9bb2f.firebasestorage.app',
    iosBundleId: 'com.example.listapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd4rpHwu4O0esMmwlkJy3CKDJoOu-n5Lc',
    appId: '1:373846261026:web:02482b72cd1b81e585f97b',
    messagingSenderId: '373846261026',
    projectId: 'fir-storage-9bb2f',
    authDomain: 'fir-storage-9bb2f.firebaseapp.com',
    storageBucket: 'fir-storage-9bb2f.firebasestorage.app',
  );
}
